import { motion } from "framer-motion";
import { useTranslation } from "react-i18next";
import "./SplashScreen.css";

// The very first thing visitors see. To change the chant text or subtitle,
// edit splash.chant / splash.subtitle in src/i18n/locales/en.json and hi.json
// — do not edit this file for wording changes.
// See EDITING_GUIDE.md → "Changing the splash chant".
export default function SplashScreen({ onEnter }) {
  const { t } = useTranslation();

  return (
    <motion.div
      className="splash"
      initial={{ opacity: 1 }}
      exit={{ opacity: 0, scale: 1.05 }}
      transition={{ duration: 0.7, ease: "easeInOut" }}
    >
      <motion.div
        className="splash-inner"
        initial={{ opacity: 0, y: 14 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.9, ease: "easeOut" }}
      >
        <span className="splash-om" aria-hidden="true">ॐ</span>
        <h1 className="splash-chant">{t("splash.chant")}</h1>
        <p className="splash-subtitle">{t("splash.subtitle")}</p>
        <button className="btn btn-primary" onClick={onEnter}>
          {t("splash.enter")}
        </button>
      </motion.div>
    </motion.div>
  );
}
